import { VaultItem } from '../types/vault';

export const INITIAL_MOCK_VAULT: VaultItem[] = [
  {
    id: 'vault-github',
    title: 'GitHub Enterprise',
    category: 'login',
    serviceCategory: 'developer',
    username: 'alex.chen@cybercore.io',
    password: 'p9$K!vN92#xQz8L@wM',
    websiteUrl: 'https://github.com/login',
    linkedApp: {
      appName: 'GitHub Desktop',
      appIdentifier: 'com.github.GitHubClient / GitHubDesktop.exe',
      customProtocolUri: 'x-github-client://',
      platform: 'desktop',
      launchSupported: true,
    },
    keyPass: {
      type: 'passkey',
      name: 'GitHub Security Key / FIDO2 Passkey',
      content: '{"credentialId":"a8f092b1c4e7","rpId":"github.com","user":"alex.chen@cybercore.io","alg":"ES256"}',
      credentialId: 'fido2_a8f092b1c4e7',
      relyingParty: 'github.com',
      createdAt: '2026-08-01T10:00:00Z',
    },
    // Standard test Base32 TOTP secret (generates live RFC 6238 codes)
    totpSecret: 'JBSWY3DPEHPK3PXP',
    totpDigits: 6,
    totpPeriod: 30,
    totpAlgorithm: 'SHA1',
    backupCodes: [
      {
        id: 'bc-gh-1',
        code: 'a9f2-8c14',
        isUsed: true,
        usedAt: '2026-09-15T14:22:00Z',
        createdAt: '2026-08-01T10:00:00Z',
        note: 'Used during macOS reinstall',
      },
      {
        id: 'bc-gh-2',
        code: '3b8e-71da',
        isUsed: false,
        createdAt: '2026-08-01T10:00:00Z',
      },
      {
        id: 'bc-gh-3',
        code: 'e4c0-99f5',
        isUsed: false,
        createdAt: '2026-08-01T10:00:00Z',
      },
      {
        id: 'bc-gh-4',
        code: '821a-6d0e',
        isUsed: false,
        createdAt: '2026-08-01T10:00:00Z',
      },
      {
        id: 'bc-gh-5',
        code: 'f1d3-45ab',
        isUsed: false,
        createdAt: '2026-08-01T10:00:00Z',
      },
    ],
    notes: 'Primary developer account with 2FA hardware key & recovery sheet.',
    tags: ['Dev', 'Production', 'VCS'],
    isFavorite: true,
    createdAt: '2026-01-10T09:00:00Z',
    updatedAt: '2026-09-20T11:30:00Z',
  },
  {
    id: 'vault-google',
    title: 'Google Cloud Platform',
    category: 'login',
    serviceCategory: 'developer',
    username: 'security-admin@dhnj.co.uk',
    password: 'W7#mR9$vL2!kP8*tQ5',
    websiteUrl: 'https://accounts.google.com',
    totpSecret: 'HXDMVJECJJWSRB3H',
    totpDigits: 6,
    totpPeriod: 30,
    totpAlgorithm: 'SHA1',
    backupCodes: [
      {
        id: 'bc-goog-1',
        code: '84920194',
        isUsed: false,
        createdAt: '2026-07-12T16:00:00Z',
      },
      {
        id: 'bc-goog-2',
        code: '30291847',
        isUsed: false,
        createdAt: '2026-07-12T16:00:00Z',
      },
      {
        id: 'bc-goog-3',
        code: '19482034',
        isUsed: false,
        createdAt: '2026-07-12T16:00:00Z',
      },
      {
        id: 'bc-goog-4',
        code: '77620194',
        isUsed: false,
        createdAt: '2026-07-12T16:00:00Z',
      },
    ],
    notes: 'Google Workspace root admin and GCP organization owner.',
    tags: ['Cloud', 'Admin', 'Critical'],
    isFavorite: true,
    createdAt: '2026-02-15T08:00:00Z',
    updatedAt: '2026-09-18T14:10:00Z',
  },
  {
    id: 'vault-aws',
    title: 'AWS Root IAM Console',
    category: 'login',
    serviceCategory: 'developer',
    username: 'ops-root@infra-mesh.net',
    password: 'C8&tX4#pZ9*mN2$qV6',
    websiteUrl: 'https://signin.aws.amazon.com/console',
    keyPass: {
      type: 'keyfile',
      name: 'aws-ops-root.key',
      content: '<?xml version="1.0" encoding="utf-8"?>\n<KeyFile>\n  <Meta>\n    <Version>1.00</Version>\n  </Meta>\n  <Key>\n    <Data>7w9K2x+Nm8BvL5qR4tX9sW3pY1zJ6mN0eA8vC3bF7dE=</Data>\n  </Key>\n</KeyFile>',
      createdAt: '2026-06-01T00:00:00Z',
    },
    totpSecret: 'KVKFKRCPNZQUYMLX',
    totpDigits: 6,
    totpPeriod: 30,
    totpAlgorithm: 'SHA1',
    backupCodes: [
      {
        id: 'bc-aws-1',
        code: '6294-8172',
        isUsed: true,
        usedAt: '2026-08-30T10:15:00Z',
        createdAt: '2026-06-01T00:00:00Z',
      },
      {
        id: 'bc-aws-2',
        code: '9014-3829',
        isUsed: true,
        usedAt: '2026-09-02T19:40:00Z',
        createdAt: '2026-06-01T00:00:00Z',
      },
      {
        id: 'bc-aws-3',
        code: '4185-9201',
        isUsed: false,
        createdAt: '2026-06-01T00:00:00Z',
      },
      {
        id: 'bc-aws-4',
        code: '7730-1849',
        isUsed: false,
        createdAt: '2026-06-01T00:00:00Z',
      },
    ],
    customFields: [
      { id: 'cf-aws-acct', label: 'AWS Account ID', value: '9842-1049-5582', type: 'text' },
      { id: 'cf-aws-alias', label: 'IAM Account Alias', value: 'infra-mesh-production', type: 'text' },
      { id: 'cf-sec-pin', label: 'Support Verification PIN', value: '592014', type: 'masked' },
    ],
    notes: 'MFA virtual device registered. 2 recovery codes remaining.',
    tags: ['DevOps', 'AWS', 'Infrastructure'],
    isFavorite: true,
    createdAt: '2026-03-01T12:00:00Z',
    updatedAt: '2026-09-22T09:45:00Z',
  },
  {
    id: 'vault-cloudflare',
    title: 'Cloudflare Zero Trust',
    category: 'login',
    serviceCategory: 'developer',
    username: 'alex@cybercore.io',
    password: 'F5!rB8#mK3$xP9*wL7',
    websiteUrl: 'https://dash.cloudflare.com/login',
    totpSecret: 'MFRGGZDFMZTWQ2LK',
    totpDigits: 6,
    totpPeriod: 30,
    totpAlgorithm: 'SHA1',
    backupCodes: [
      {
        id: 'bc-cf-1',
        code: '5819-2048',
        isUsed: true,
        usedAt: '2026-09-10T12:00:00Z',
        createdAt: '2026-05-15T00:00:00Z',
      },
      {
        id: 'bc-cf-2',
        code: '9301-4472',
        isUsed: true,
        usedAt: '2026-09-21T08:30:00Z',
        createdAt: '2026-05-15T00:00:00Z',
      },
      {
        id: 'bc-cf-3',
        code: '1849-6032',
        isUsed: false,
        createdAt: '2026-05-15T00:00:00Z',
      },
    ],
    notes: 'WARNING: Only 1 active backup code remaining. Regenerate soon!',
    tags: ['DNS', 'Security', 'Edge'],
    isFavorite: false,
    createdAt: '2026-04-10T11:00:00Z',
    updatedAt: '2026-09-25T16:20:00Z',
  },
  {
    id: 'vault-discord',
    title: 'Discord Developer Portal',
    category: 'login',
    serviceCategory: 'social',
    username: 'alex_botmaster',
    password: 'd8#K2$vN9!xM4*rP6',
    websiteUrl: 'https://discord.com/login',
    linkedApp: {
      appName: 'Discord Desktop',
      appIdentifier: 'com.hnc.Discord / Discord.exe',
      customProtocolUri: 'discord://',
      platform: 'universal',
      launchSupported: true,
    },
    totpSecret: 'GEZDGNBVGY3TQOJQ',
    totpDigits: 6,
    totpPeriod: 30,
    totpAlgorithm: 'SHA1',
    backupCodes: [
      {
        id: 'bc-disc-1',
        code: 'k8m2-9p1a',
        isUsed: false,
        createdAt: '2026-06-20T10:00:00Z',
      },
      {
        id: 'bc-disc-2',
        code: '4x7n-2v9q',
        isUsed: false,
        createdAt: '2026-06-20T10:00:00Z',
      },
    ],
    notes: 'Bot application token and verified guild ownership.',
    tags: ['Dev', 'Community'],
    isFavorite: false,
    createdAt: '2026-05-01T15:00:00Z',
    updatedAt: '2026-09-12T10:00:00Z',
  },
  {
    id: 'vault-stripe',
    title: 'Stripe Merchant Dashboard',
    category: 'login',
    serviceCategory: 'finance',
    username: 'billing@cybercore.io',
    password: 'S3*qW8!zT5#bN9$vK1',
    websiteUrl: 'https://dashboard.stripe.com/login',
    totpSecret: 'NBSWY3DPEHPK3PXP',
    totpDigits: 6,
    totpPeriod: 30,
    totpAlgorithm: 'SHA1',
    backupCodes: [
      {
        id: 'bc-str-1',
        code: '90412850',
        isUsed: false,
        createdAt: '2026-08-10T14:00:00Z',
      },
      {
        id: 'bc-str-2',
        code: '61729403',
        isUsed: false,
        createdAt: '2026-08-10T14:00:00Z',
      },
      {
        id: 'bc-str-3',
        code: '82049184',
        isUsed: false,
        createdAt: '2026-08-10T14:00:00Z',
      },
    ],
    notes: 'Payout settings and webhooks management.',
    tags: ['Finance', 'Stripe'],
    isFavorite: false,
    createdAt: '2026-06-15T09:00:00Z',
    updatedAt: '2026-09-19T17:00:00Z',
  },
  {
    id: 'vault-passport-uk',
    title: 'UK Biometric Passport',
    category: 'identity_doc',
    serviceCategory: 'identity',
    username: 'ALEX CHEN',
    password: '',
    websiteUrl: 'https://www.gov.uk/browse/abroad/passports',
    backupCodes: [],
    identityDoc: {
      documentType: 'passport',
      fullName: 'ALEX CHEN',
      documentNumber: '539108427',
      issuingCountry: 'United Kingdom',
      nationality: 'BRITISH CITIZEN',
      dateOfBirth: '1992-05-14',
      issueDate: '2021-08-20',
      expiryDate: '2031-08-20',
      gender: 'Male',
      issuingStateOrAuthority: 'HM Passport Office',
      customFields: [
        { id: 'f1', label: 'Place of Birth', value: 'London, GBR', type: 'text' },
        { id: 'f2', label: 'Machine Readable Zone (MRZ)', value: 'P<GBRCHEN<<ALEX<<<<<<<<<<<<<<<<<<<<5391084278GBR9205140M3108200<<<<<<<<<<<<<<04', type: 'masked' },
      ],
    },
    notes: 'Primary international travel document. Keep in fireproof safe when not traveling.',
    tags: ['Passport', 'Travel', 'Identity'],
    isFavorite: true,
    createdAt: '2026-01-15T10:00:00Z',
    updatedAt: '2026-09-10T12:00:00Z',
  },
  {
    id: 'vault-driving-license',
    title: 'UK Driving Licence',
    category: 'identity_doc',
    serviceCategory: 'identity',
    username: 'ALEX CHEN',
    password: '',
    websiteUrl: 'https://www.gov.uk/view-driving-licence',
    backupCodes: [],
    identityDoc: {
      documentType: 'drivers_license',
      fullName: 'ALEXANDER CHEN',
      documentNumber: 'CHEN952054A99AL',
      issuingCountry: 'United Kingdom',
      issuingStateOrAuthority: 'DVLA Swansea',
      dateOfBirth: '1992-05-14',
      issueDate: '2023-03-10',
      expiryDate: '2033-03-10',
      address: '42 Baker Street, Marylebone, London NW1 6XE',
      customFields: [
        { id: 'f3', label: 'Entitlement Categories', value: 'AM / A / B1 / B / BE', type: 'text' },
        { id: 'f4', label: 'Driver Number / Issue No', value: '01', type: 'text' },
      ],
    },
    notes: 'Photocard driving licence. Registered vehicle owner.',
    tags: ['License', 'Driving', 'Transport'],
    isFavorite: false,
    createdAt: '2026-03-20T14:00:00Z',
    updatedAt: '2026-08-15T09:30:00Z',
  },
  {
    id: 'vault-custom-insurance',
    title: 'Global Health & Medical Card',
    category: 'identity_doc',
    serviceCategory: 'identity',
    username: 'Alex Chen',
    password: '',
    websiteUrl: 'https://bupa.co.uk',
    backupCodes: [],
    identityDoc: {
      documentType: 'custom_document',
      customTypeName: 'Health Insurance Card',
      fullName: 'Alex Chen',
      documentNumber: 'BUP-9824-001X',
      issuingCountry: 'United Kingdom',
      issuingStateOrAuthority: 'Bupa International Healthcare',
      expiryDate: '2027-12-31',
      customFields: [
        { id: 'f5', label: 'Policy Group Number', value: 'GRP-TECH-4402', type: 'text' },
        { id: 'f6', label: 'Emergency Hotline', value: '+44 (0) 20 7123 4567', type: 'text' },
        { id: 'f7', label: 'Coverage Tier', value: 'Worldwide Comprehensive + Dental', type: 'text' },
        { id: 'f8', label: 'National Health ID / NHS No', value: '482 910 4721', type: 'masked' },
      ],
    },
    notes: 'Present at medical reception or international clinics.',
    tags: ['Health', 'Insurance', 'Emergency'],
    isFavorite: false,
    createdAt: '2026-04-05T11:00:00Z',
    updatedAt: '2026-09-01T15:20:00Z',
  },
  {
    id: 'vault-ledger-nano',
    title: 'Ledger Nano X Hardware Wallet',
    category: 'custom',
    customCategoryName: 'Crypto Hardware Wallet',
    serviceCategory: 'finance',
    username: 'alex.chen',
    password: '',
    websiteUrl: 'https://ledger.com',
    backupCodes: [],
    customFields: [
      { id: 'cf-pin', label: 'Device Security PIN', value: '749201', type: 'masked' },
      { id: 'cf-derivation', label: 'Derivation Path', value: "m/44'/60'/0'/0/0 (ETH / EVM)", type: 'text' },
      { id: 'cf-firmware', label: 'Firmware Version', value: 'v2.2.4-SecureOS', type: 'text' },
      { id: 'cf-passphrase', label: '25th Word Passphrase', value: 'coral-obsidian-quantum-vault', type: 'masked' },
      { id: 'cf-warranty', label: 'Warranty Expiry', value: '2028-12-31', type: 'date' },
    ],
    notes: 'Physical recovery sheet in steel capsule in London safety deposit box.',
    tags: ['Crypto', 'Ledger', 'HardwareWallet', 'Security'],
    isFavorite: true,
    createdAt: '2026-02-01T10:00:00Z',
    updatedAt: '2026-09-15T08:00:00Z',
  },
];
